{% set name = "pyodbc" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2fe0e063d8fb66efd0ac6dc39236c4de1a45f17c33eaded0d553d21c199f4d05

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - unixodbc {{ unixodbc }}  # [unix]
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - pyodbc
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Cannot invoke upstream tests due to lack of databse connection
    # E   pyodbc.InterfaceError: ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found and no default driver specified (0) (SQLDriverConnect)')
    # - pytest -v tests

about:
  home: https://github.com/mkleehammer/pyodbc
  license: MIT-0
  license_family: MIT
  license_file: LICENSE.txt
  summary: DB API Module for ODBC
  description: |
    pyodbc is a Python DB API 2 module for ODBC. This project provides an
    up-to-date, convenient interface to ODBC using native data types like
    datetime and decimal.
  doc_url: https://mkleehammer.github.io/pyodbc
  dev_url: https://github.com/mkleehammer/pyodbc

extra:
  recipe-maintainers:
    - nehaljwani
