{% set name = "pyodbc" %}
{% set version = "4.0.32" %}
{% set sha256 = "4ed213d0f67d639d03d37de52a613a4e5a0da113e6d0d56e90dca09d7060470c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # no sdict was uploaded to PyPI for the 4.0.30 release, use the GitHub archive.
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/mkleehammer/pyodbc/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - setup.patch  # [unix]

build:
  skip: True  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - patch  # [not win]
    - m2-patch  # [win]

  host:
    - python
    - pip
    - setuptools
    - unixodbc   # [unix]
    - wheel
  run:
    - python >=3.6

test:
  imports:
    - pyodbc
  requires:
    - pip
    - python
  commands:
    - pip check

about:
  home: https://github.com/mkleehammer/pyodbc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'DB API Module for ODBC'
  description: |
    pyodbc is a Python DB API 2 module for ODBC. This project provides an
    up-to-date, convenient interface to ODBC using native data types like
    datetime and decimal.
  doc_url: http://mkleehammer.github.io/pyodbc/
  doc_source_url: https://github.com/mkleehammer/pyodbc/blob/master/docs/index.md
  dev_url: https://github.com/mkleehammer/pyodbc

extra:
  recipe-maintainers:
    - nehaljwani
