{% set name = "pyodbc" %}
{% set version = "4.0.21" %}
{% set sha256 = "9655f84ca9e5cb2dfffff705601017420c840d55271ba62dd44f05383eff0329" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - setup.patch  # [unix]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - unixodbc 2.3.4  # [unix]

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    - unixodbc 2.3.4  # [unix]

test:
  imports:
    - pyodbc

about:
  home: https://github.com/mkleehammer/pyodbc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'DB API Module for ODBC'
  description: |
    pyodbc is a Python DB API 2 module for ODBC. This project provides an
    up-to-date, convenient interface to ODBC using native data types like
    datetime and decimal.
  doc_url: http://mkleehammer.github.io/pyodbc/
  doc_source_url: https://github.com/mkleehammer/pyodbc/blob/master/docs/index.md
  dev_url: https://github.com/mkleehammer/pyodbc

extra:
  recipe-maintainers:
    - nehaljwani
