travis:
  secure:
    BINSTAR_TOKEN: nzmqaDlC3loMmjDQ6t4NX7WJ4IWlRa+V0zXRs9aM46CIBOjLeBL9AempbEb54VPiL760tR6ONI3YNoPmPDPX62lFsszyrwMhDh1e4Letzcz1oHEEwKPKYb+0pw0uRr9c2s+UuJT6fZLg6fp3XHDw/1dCKh/FCk+ddStneLIu7yPndFvHk4vLg7A56q/JjVgssZlrqbA6DnQTC9pA3bM5U5YfU0G36t4kuBzFcAxALMRMsm/zrMm8b/Y55zg1ARNdsklLtTU88ZmpLKOxbBe077mun1Nxwdix3TdIna2SDSN2dhJg2okNwSwACzlb1KjArTGm9iQfFlOLMVBQO+UtCzl5doNv9NV5ifESUnMRo1Sp0KjP/H1wY1MrTkRiiowp1piKydiAR8kYa/NlsAfqHVkWu/ujVdM2gTIjixNlTMjj0Kg0iw2JpOOxRuJokOUxt4h7NHG3aXz2h7K/rRZbzhtvYH53DPkUmJvUEaydW4LVMTCOR+sTULEKzlEQm3uciEG8AA1jAfy4iGS/M773lu8XeiOLYE9jCpOnQB6uDGetErTqbp9Kscu9Nnj2FDLjUoZiwguP8lh2xnv6Fu4O6LyLoSwZG8P8Ojbm30nChG2027eA9w48Fy/w79dHG7qTbaavDCP/AK5kBgHjfDdXnnoKTF+fY7Vc8quTto5l4aI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
